name: 'Actions AWS Auth'
description: 'Provision and AWS infra to Authenticate users'
inputs:
  action: 
    description: "Desire outcome: deploy or delete"
    required: false
    default: "deploy"
  name:
    description: Identifier name
    required: true
  domain:
    description: Domain name
    required: true

runs:
  using: "composite"
  steps:
    - name: Destroy infrastructure
      working-directory: ${{ github.action_path }}
      if: ${{ inputs.action=='delete' }}
      shell: bash
      run: |
        sam build
        sam delete \
        --no-prompts \
        --stack-name auth-${{ inputs.name }}-${{ github.repository_id }}

    - name: Applying infrastructure 🚀
      working-directory: ${{ github.action_path }}
      if: ${{ inputs.action=='deploy' }}
      shell: bash
      run: |
        sam build
        sam deploy \
        --resolve-s3 true \
        --stack-name auth-${{ inputs.name }}-${{ github.repository_id }} \
        --capabilities CAPABILITY_IAM \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides \
        DomainName="${{ inputs.domain }}" \
        DomainHostedZoneId="Z0674300MVO8RX9JHZFL"
    - name: export UserPoolId and UserPoolClient
      if: ${{ inputs.action=='deploy' }}
      shell: bash
      run: |
        export UserPoolArn=$(aws cloudformation describe-stacks --stack-name auth-${{ inputs.name }}-${{ github.repository_id }} --query "Stacks[0].Outputs[?OutputKey=='UserPoolArn'].OutputValue" --output text)
        export UserPoolClientId=$(aws cloudformation describe-stacks --stack-name auth-${{ inputs.name }}-${{ github.repository_id }} --query "Stacks[0].Outputs[?OutputKey=='ClientId'].OutputValue" --output text)
        echo "UserPoolArn=${UserPoolArn}" >> $GITHUB_ENV
        echo "UserPoolClientId=${UserPoolClientId}" >> $GITHUB_ENV