AWSTemplateFormatVersion: 2010-09-09
Description: >-
  actions-aws-auth
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  DomainName:
    Type: String
  DomainHostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${DomainName}
      DomainValidationOptions:
       - DomainName: !Sub ${DomainName}
         HostedZoneId: !Ref DomainHostedZoneId
      ValidationMethod: DNS
      SubjectAlternativeNames: 
      - !Sub "*.${DomainName}"
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${AWS::StackName}
      UserPoolTier: ESSENTIALS
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true # required for SAML auth
          Required: true
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      ManagedLoginVersion: 2
      UserPoolId: !Ref UserPool
      Domain: !Sub "auth.${DomainName}"
      CustomDomainConfig:
        CertificateArn: !Ref Certificate
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub ${AWS::StackName}
      GenerateSecret: true
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Sub "https://${DomainName}/oauth2/idpresponse"
      LogoutURLs:
        - "https://www.google.com"
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DomainHostedZoneId
      Name: !Sub "auth.${DomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
        EvaluateTargetHealth: false
  ManagedLogin:
    Type: AWS::Cognito::ManagedLoginBranding
    Properties:
      UserPoolId: !Ref UserPool
      UseCognitoProvidedValues: true
      ClientId: !Sub ${UserPoolClient.ClientId}
Outputs:
  UserPoolArn:
    Value: !Sub ${UserPool.Arn}
  ClientId:
    Value: !Sub ${UserPoolClient.ClientId}
  Certificate:
    Value: !Ref Certificate